Metrics/LineLength:
  Enabled: false 

Metrics/ClassLength:
  Enabled: false 

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5  
Metrics/PerceivedComplexity:
  Enabled: false 
